/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.leftybeauty.schema.avro;
@org.apache.avro.specific.AvroGenerated
public enum LeftyPaymentStatusEnum implements org.apache.avro.generic.GenericEnumSymbol<LeftyPaymentStatusEnum> {
  Approved, Declined  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"LeftyPaymentStatusEnum\",\"namespace\":\"com.leftybeauty.schema.avro\",\"symbols\":[\"Approved\",\"Declined\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
