/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.leftybeauty.schema.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LeftyUserFeedbackSummaryView extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4571060753152082865L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LeftyUserFeedbackSummaryView\",\"namespace\":\"com.leftybeauty.schema.avro\",\"fields\":[{\"name\":\"leftyUserId\",\"type\":\"string\"},{\"name\":\"ratingAverage\",\"type\":\"double\"},{\"name\":\"feedbackTarget\",\"type\":{\"type\":\"enum\",\"name\":\"LeftyUserTypeEnum\",\"symbols\":[\"Client\",\"Provider\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LeftyUserFeedbackSummaryView> ENCODER =
      new BinaryMessageEncoder<LeftyUserFeedbackSummaryView>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LeftyUserFeedbackSummaryView> DECODER =
      new BinaryMessageDecoder<LeftyUserFeedbackSummaryView>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LeftyUserFeedbackSummaryView> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LeftyUserFeedbackSummaryView> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LeftyUserFeedbackSummaryView> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LeftyUserFeedbackSummaryView>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LeftyUserFeedbackSummaryView to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LeftyUserFeedbackSummaryView from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LeftyUserFeedbackSummaryView instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LeftyUserFeedbackSummaryView fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence leftyUserId;
   private double ratingAverage;
   private com.leftybeauty.schema.avro.LeftyUserTypeEnum feedbackTarget;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LeftyUserFeedbackSummaryView() {}

  /**
   * All-args constructor.
   * @param leftyUserId The new value for leftyUserId
   * @param ratingAverage The new value for ratingAverage
   * @param feedbackTarget The new value for feedbackTarget
   */
  public LeftyUserFeedbackSummaryView(java.lang.CharSequence leftyUserId, java.lang.Double ratingAverage, com.leftybeauty.schema.avro.LeftyUserTypeEnum feedbackTarget) {
    this.leftyUserId = leftyUserId;
    this.ratingAverage = ratingAverage;
    this.feedbackTarget = feedbackTarget;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return leftyUserId;
    case 1: return ratingAverage;
    case 2: return feedbackTarget;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: leftyUserId = (java.lang.CharSequence)value$; break;
    case 1: ratingAverage = (java.lang.Double)value$; break;
    case 2: feedbackTarget = (com.leftybeauty.schema.avro.LeftyUserTypeEnum)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'leftyUserId' field.
   * @return The value of the 'leftyUserId' field.
   */
  public java.lang.CharSequence getLeftyUserId() {
    return leftyUserId;
  }


  /**
   * Sets the value of the 'leftyUserId' field.
   * @param value the value to set.
   */
  public void setLeftyUserId(java.lang.CharSequence value) {
    this.leftyUserId = value;
  }

  /**
   * Gets the value of the 'ratingAverage' field.
   * @return The value of the 'ratingAverage' field.
   */
  public double getRatingAverage() {
    return ratingAverage;
  }


  /**
   * Sets the value of the 'ratingAverage' field.
   * @param value the value to set.
   */
  public void setRatingAverage(double value) {
    this.ratingAverage = value;
  }

  /**
   * Gets the value of the 'feedbackTarget' field.
   * @return The value of the 'feedbackTarget' field.
   */
  public com.leftybeauty.schema.avro.LeftyUserTypeEnum getFeedbackTarget() {
    return feedbackTarget;
  }


  /**
   * Sets the value of the 'feedbackTarget' field.
   * @param value the value to set.
   */
  public void setFeedbackTarget(com.leftybeauty.schema.avro.LeftyUserTypeEnum value) {
    this.feedbackTarget = value;
  }

  /**
   * Creates a new LeftyUserFeedbackSummaryView RecordBuilder.
   * @return A new LeftyUserFeedbackSummaryView RecordBuilder
   */
  public static com.leftybeauty.schema.avro.LeftyUserFeedbackSummaryView.Builder newBuilder() {
    return new com.leftybeauty.schema.avro.LeftyUserFeedbackSummaryView.Builder();
  }

  /**
   * Creates a new LeftyUserFeedbackSummaryView RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LeftyUserFeedbackSummaryView RecordBuilder
   */
  public static com.leftybeauty.schema.avro.LeftyUserFeedbackSummaryView.Builder newBuilder(com.leftybeauty.schema.avro.LeftyUserFeedbackSummaryView.Builder other) {
    if (other == null) {
      return new com.leftybeauty.schema.avro.LeftyUserFeedbackSummaryView.Builder();
    } else {
      return new com.leftybeauty.schema.avro.LeftyUserFeedbackSummaryView.Builder(other);
    }
  }

  /**
   * Creates a new LeftyUserFeedbackSummaryView RecordBuilder by copying an existing LeftyUserFeedbackSummaryView instance.
   * @param other The existing instance to copy.
   * @return A new LeftyUserFeedbackSummaryView RecordBuilder
   */
  public static com.leftybeauty.schema.avro.LeftyUserFeedbackSummaryView.Builder newBuilder(com.leftybeauty.schema.avro.LeftyUserFeedbackSummaryView other) {
    if (other == null) {
      return new com.leftybeauty.schema.avro.LeftyUserFeedbackSummaryView.Builder();
    } else {
      return new com.leftybeauty.schema.avro.LeftyUserFeedbackSummaryView.Builder(other);
    }
  }

  /**
   * RecordBuilder for LeftyUserFeedbackSummaryView instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LeftyUserFeedbackSummaryView>
    implements org.apache.avro.data.RecordBuilder<LeftyUserFeedbackSummaryView> {

    private java.lang.CharSequence leftyUserId;
    private double ratingAverage;
    private com.leftybeauty.schema.avro.LeftyUserTypeEnum feedbackTarget;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.leftybeauty.schema.avro.LeftyUserFeedbackSummaryView.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.leftyUserId)) {
        this.leftyUserId = data().deepCopy(fields()[0].schema(), other.leftyUserId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.ratingAverage)) {
        this.ratingAverage = data().deepCopy(fields()[1].schema(), other.ratingAverage);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.feedbackTarget)) {
        this.feedbackTarget = data().deepCopy(fields()[2].schema(), other.feedbackTarget);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing LeftyUserFeedbackSummaryView instance
     * @param other The existing instance to copy.
     */
    private Builder(com.leftybeauty.schema.avro.LeftyUserFeedbackSummaryView other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.leftyUserId)) {
        this.leftyUserId = data().deepCopy(fields()[0].schema(), other.leftyUserId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ratingAverage)) {
        this.ratingAverage = data().deepCopy(fields()[1].schema(), other.ratingAverage);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.feedbackTarget)) {
        this.feedbackTarget = data().deepCopy(fields()[2].schema(), other.feedbackTarget);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'leftyUserId' field.
      * @return The value.
      */
    public java.lang.CharSequence getLeftyUserId() {
      return leftyUserId;
    }


    /**
      * Sets the value of the 'leftyUserId' field.
      * @param value The value of 'leftyUserId'.
      * @return This builder.
      */
    public com.leftybeauty.schema.avro.LeftyUserFeedbackSummaryView.Builder setLeftyUserId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.leftyUserId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'leftyUserId' field has been set.
      * @return True if the 'leftyUserId' field has been set, false otherwise.
      */
    public boolean hasLeftyUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'leftyUserId' field.
      * @return This builder.
      */
    public com.leftybeauty.schema.avro.LeftyUserFeedbackSummaryView.Builder clearLeftyUserId() {
      leftyUserId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ratingAverage' field.
      * @return The value.
      */
    public double getRatingAverage() {
      return ratingAverage;
    }


    /**
      * Sets the value of the 'ratingAverage' field.
      * @param value The value of 'ratingAverage'.
      * @return This builder.
      */
    public com.leftybeauty.schema.avro.LeftyUserFeedbackSummaryView.Builder setRatingAverage(double value) {
      validate(fields()[1], value);
      this.ratingAverage = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ratingAverage' field has been set.
      * @return True if the 'ratingAverage' field has been set, false otherwise.
      */
    public boolean hasRatingAverage() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ratingAverage' field.
      * @return This builder.
      */
    public com.leftybeauty.schema.avro.LeftyUserFeedbackSummaryView.Builder clearRatingAverage() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'feedbackTarget' field.
      * @return The value.
      */
    public com.leftybeauty.schema.avro.LeftyUserTypeEnum getFeedbackTarget() {
      return feedbackTarget;
    }


    /**
      * Sets the value of the 'feedbackTarget' field.
      * @param value The value of 'feedbackTarget'.
      * @return This builder.
      */
    public com.leftybeauty.schema.avro.LeftyUserFeedbackSummaryView.Builder setFeedbackTarget(com.leftybeauty.schema.avro.LeftyUserTypeEnum value) {
      validate(fields()[2], value);
      this.feedbackTarget = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'feedbackTarget' field has been set.
      * @return True if the 'feedbackTarget' field has been set, false otherwise.
      */
    public boolean hasFeedbackTarget() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'feedbackTarget' field.
      * @return This builder.
      */
    public com.leftybeauty.schema.avro.LeftyUserFeedbackSummaryView.Builder clearFeedbackTarget() {
      feedbackTarget = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LeftyUserFeedbackSummaryView build() {
      try {
        LeftyUserFeedbackSummaryView record = new LeftyUserFeedbackSummaryView();
        record.leftyUserId = fieldSetFlags()[0] ? this.leftyUserId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.ratingAverage = fieldSetFlags()[1] ? this.ratingAverage : (java.lang.Double) defaultValue(fields()[1]);
        record.feedbackTarget = fieldSetFlags()[2] ? this.feedbackTarget : (com.leftybeauty.schema.avro.LeftyUserTypeEnum) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LeftyUserFeedbackSummaryView>
    WRITER$ = (org.apache.avro.io.DatumWriter<LeftyUserFeedbackSummaryView>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LeftyUserFeedbackSummaryView>
    READER$ = (org.apache.avro.io.DatumReader<LeftyUserFeedbackSummaryView>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.leftyUserId);

    out.writeDouble(this.ratingAverage);

    out.writeEnum(this.feedbackTarget.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.leftyUserId = in.readString(this.leftyUserId instanceof Utf8 ? (Utf8)this.leftyUserId : null);

      this.ratingAverage = in.readDouble();

      this.feedbackTarget = com.leftybeauty.schema.avro.LeftyUserTypeEnum.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.leftyUserId = in.readString(this.leftyUserId instanceof Utf8 ? (Utf8)this.leftyUserId : null);
          break;

        case 1:
          this.ratingAverage = in.readDouble();
          break;

        case 2:
          this.feedbackTarget = com.leftybeauty.schema.avro.LeftyUserTypeEnum.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










