/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.leftybeauty.schema.avro;
@org.apache.avro.specific.AvroGenerated
public enum MimeType implements org.apache.avro.generic.GenericEnumSymbol<MimeType> {
  TEXT, JSON, JPEG  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MimeType\",\"namespace\":\"com.leftybeauty.schema.avro\",\"symbols\":[\"TEXT\",\"JSON\",\"JPEG\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
