/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.leftybeauty.schema.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PaymentMethodValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4822800291267144299L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PaymentMethodValue\",\"namespace\":\"com.leftybeauty.schema.avro\",\"fields\":[{\"name\":\"paymentMethodId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"last4\",\"type\":\"int\"},{\"name\":\"expiration\",\"type\":\"int\"},{\"name\":\"type\",\"type\":{\"type\":\"enum\",\"name\":\"PaymentMethodTypeEnum\",\"symbols\":[\"Visa\",\"Mastercard\",\"Amex\",\"Discover\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PaymentMethodValue> ENCODER =
      new BinaryMessageEncoder<PaymentMethodValue>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PaymentMethodValue> DECODER =
      new BinaryMessageDecoder<PaymentMethodValue>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PaymentMethodValue> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PaymentMethodValue> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PaymentMethodValue> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PaymentMethodValue>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PaymentMethodValue to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PaymentMethodValue from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PaymentMethodValue instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PaymentMethodValue fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence paymentMethodId;
   private int last4;
   private int expiration;
   private com.leftybeauty.schema.avro.PaymentMethodTypeEnum type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PaymentMethodValue() {}

  /**
   * All-args constructor.
   * @param paymentMethodId The new value for paymentMethodId
   * @param last4 The new value for last4
   * @param expiration The new value for expiration
   * @param type The new value for type
   */
  public PaymentMethodValue(java.lang.CharSequence paymentMethodId, java.lang.Integer last4, java.lang.Integer expiration, com.leftybeauty.schema.avro.PaymentMethodTypeEnum type) {
    this.paymentMethodId = paymentMethodId;
    this.last4 = last4;
    this.expiration = expiration;
    this.type = type;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return paymentMethodId;
    case 1: return last4;
    case 2: return expiration;
    case 3: return type;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: paymentMethodId = (java.lang.CharSequence)value$; break;
    case 1: last4 = (java.lang.Integer)value$; break;
    case 2: expiration = (java.lang.Integer)value$; break;
    case 3: type = (com.leftybeauty.schema.avro.PaymentMethodTypeEnum)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'paymentMethodId' field.
   * @return The value of the 'paymentMethodId' field.
   */
  public java.lang.CharSequence getPaymentMethodId() {
    return paymentMethodId;
  }


  /**
   * Sets the value of the 'paymentMethodId' field.
   * @param value the value to set.
   */
  public void setPaymentMethodId(java.lang.CharSequence value) {
    this.paymentMethodId = value;
  }

  /**
   * Gets the value of the 'last4' field.
   * @return The value of the 'last4' field.
   */
  public int getLast4() {
    return last4;
  }


  /**
   * Sets the value of the 'last4' field.
   * @param value the value to set.
   */
  public void setLast4(int value) {
    this.last4 = value;
  }

  /**
   * Gets the value of the 'expiration' field.
   * @return The value of the 'expiration' field.
   */
  public int getExpiration() {
    return expiration;
  }


  /**
   * Sets the value of the 'expiration' field.
   * @param value the value to set.
   */
  public void setExpiration(int value) {
    this.expiration = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public com.leftybeauty.schema.avro.PaymentMethodTypeEnum getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(com.leftybeauty.schema.avro.PaymentMethodTypeEnum value) {
    this.type = value;
  }

  /**
   * Creates a new PaymentMethodValue RecordBuilder.
   * @return A new PaymentMethodValue RecordBuilder
   */
  public static com.leftybeauty.schema.avro.PaymentMethodValue.Builder newBuilder() {
    return new com.leftybeauty.schema.avro.PaymentMethodValue.Builder();
  }

  /**
   * Creates a new PaymentMethodValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PaymentMethodValue RecordBuilder
   */
  public static com.leftybeauty.schema.avro.PaymentMethodValue.Builder newBuilder(com.leftybeauty.schema.avro.PaymentMethodValue.Builder other) {
    if (other == null) {
      return new com.leftybeauty.schema.avro.PaymentMethodValue.Builder();
    } else {
      return new com.leftybeauty.schema.avro.PaymentMethodValue.Builder(other);
    }
  }

  /**
   * Creates a new PaymentMethodValue RecordBuilder by copying an existing PaymentMethodValue instance.
   * @param other The existing instance to copy.
   * @return A new PaymentMethodValue RecordBuilder
   */
  public static com.leftybeauty.schema.avro.PaymentMethodValue.Builder newBuilder(com.leftybeauty.schema.avro.PaymentMethodValue other) {
    if (other == null) {
      return new com.leftybeauty.schema.avro.PaymentMethodValue.Builder();
    } else {
      return new com.leftybeauty.schema.avro.PaymentMethodValue.Builder(other);
    }
  }

  /**
   * RecordBuilder for PaymentMethodValue instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PaymentMethodValue>
    implements org.apache.avro.data.RecordBuilder<PaymentMethodValue> {

    private java.lang.CharSequence paymentMethodId;
    private int last4;
    private int expiration;
    private com.leftybeauty.schema.avro.PaymentMethodTypeEnum type;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.leftybeauty.schema.avro.PaymentMethodValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.paymentMethodId)) {
        this.paymentMethodId = data().deepCopy(fields()[0].schema(), other.paymentMethodId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.last4)) {
        this.last4 = data().deepCopy(fields()[1].schema(), other.last4);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.expiration)) {
        this.expiration = data().deepCopy(fields()[2].schema(), other.expiration);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.type)) {
        this.type = data().deepCopy(fields()[3].schema(), other.type);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing PaymentMethodValue instance
     * @param other The existing instance to copy.
     */
    private Builder(com.leftybeauty.schema.avro.PaymentMethodValue other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.paymentMethodId)) {
        this.paymentMethodId = data().deepCopy(fields()[0].schema(), other.paymentMethodId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.last4)) {
        this.last4 = data().deepCopy(fields()[1].schema(), other.last4);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.expiration)) {
        this.expiration = data().deepCopy(fields()[2].schema(), other.expiration);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.type)) {
        this.type = data().deepCopy(fields()[3].schema(), other.type);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'paymentMethodId' field.
      * @return The value.
      */
    public java.lang.CharSequence getPaymentMethodId() {
      return paymentMethodId;
    }


    /**
      * Sets the value of the 'paymentMethodId' field.
      * @param value The value of 'paymentMethodId'.
      * @return This builder.
      */
    public com.leftybeauty.schema.avro.PaymentMethodValue.Builder setPaymentMethodId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.paymentMethodId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentMethodId' field has been set.
      * @return True if the 'paymentMethodId' field has been set, false otherwise.
      */
    public boolean hasPaymentMethodId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'paymentMethodId' field.
      * @return This builder.
      */
    public com.leftybeauty.schema.avro.PaymentMethodValue.Builder clearPaymentMethodId() {
      paymentMethodId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'last4' field.
      * @return The value.
      */
    public int getLast4() {
      return last4;
    }


    /**
      * Sets the value of the 'last4' field.
      * @param value The value of 'last4'.
      * @return This builder.
      */
    public com.leftybeauty.schema.avro.PaymentMethodValue.Builder setLast4(int value) {
      validate(fields()[1], value);
      this.last4 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'last4' field has been set.
      * @return True if the 'last4' field has been set, false otherwise.
      */
    public boolean hasLast4() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'last4' field.
      * @return This builder.
      */
    public com.leftybeauty.schema.avro.PaymentMethodValue.Builder clearLast4() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'expiration' field.
      * @return The value.
      */
    public int getExpiration() {
      return expiration;
    }


    /**
      * Sets the value of the 'expiration' field.
      * @param value The value of 'expiration'.
      * @return This builder.
      */
    public com.leftybeauty.schema.avro.PaymentMethodValue.Builder setExpiration(int value) {
      validate(fields()[2], value);
      this.expiration = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'expiration' field has been set.
      * @return True if the 'expiration' field has been set, false otherwise.
      */
    public boolean hasExpiration() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'expiration' field.
      * @return This builder.
      */
    public com.leftybeauty.schema.avro.PaymentMethodValue.Builder clearExpiration() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public com.leftybeauty.schema.avro.PaymentMethodTypeEnum getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public com.leftybeauty.schema.avro.PaymentMethodValue.Builder setType(com.leftybeauty.schema.avro.PaymentMethodTypeEnum value) {
      validate(fields()[3], value);
      this.type = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public com.leftybeauty.schema.avro.PaymentMethodValue.Builder clearType() {
      type = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PaymentMethodValue build() {
      try {
        PaymentMethodValue record = new PaymentMethodValue();
        record.paymentMethodId = fieldSetFlags()[0] ? this.paymentMethodId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.last4 = fieldSetFlags()[1] ? this.last4 : (java.lang.Integer) defaultValue(fields()[1]);
        record.expiration = fieldSetFlags()[2] ? this.expiration : (java.lang.Integer) defaultValue(fields()[2]);
        record.type = fieldSetFlags()[3] ? this.type : (com.leftybeauty.schema.avro.PaymentMethodTypeEnum) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PaymentMethodValue>
    WRITER$ = (org.apache.avro.io.DatumWriter<PaymentMethodValue>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PaymentMethodValue>
    READER$ = (org.apache.avro.io.DatumReader<PaymentMethodValue>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.paymentMethodId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.paymentMethodId);
    }

    out.writeInt(this.last4);

    out.writeInt(this.expiration);

    out.writeEnum(this.type.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.paymentMethodId = null;
      } else {
        this.paymentMethodId = in.readString(this.paymentMethodId instanceof Utf8 ? (Utf8)this.paymentMethodId : null);
      }

      this.last4 = in.readInt();

      this.expiration = in.readInt();

      this.type = com.leftybeauty.schema.avro.PaymentMethodTypeEnum.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.paymentMethodId = null;
          } else {
            this.paymentMethodId = in.readString(this.paymentMethodId instanceof Utf8 ? (Utf8)this.paymentMethodId : null);
          }
          break;

        case 1:
          this.last4 = in.readInt();
          break;

        case 2:
          this.expiration = in.readInt();
          break;

        case 3:
          this.type = com.leftybeauty.schema.avro.PaymentMethodTypeEnum.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










